   version: '3'
   services:
     db:
       image: postgres
       environment:
         POSTGRES_PASSWORD: admin
     backend:
       build: ./src/Api
       depends_on:
         - db
     frontend:
       build: ./src/App/gestoralmacen
       depends_on:
         - backend