version: '3'
services:
 db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
 backend:
    build: ./src/Api
    image: dukagin/backend:dev
    depends_on:
      - db
 frontend:
    build: ./src/App/gestoralmacen
    image: dukagin/frontend:dev
    depends_on:
      - backend