name: CI

on: [push]

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: Gestor-de-almacenes

    - name: Build and test
      run: |
        cd Gestor-de-almacenes
        docker-compose build
        docker-compose up -d
        docker-compose down