name: CI

on: [push]

jobs:
 dotnet-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: Gestor-de-almacenes

    - name: Build and test
      run: |
        cd Gestor-de-almacenes
        docker-compose build
        docker-compose up -d
        docker-compose down
 node-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Change to Node.js app directory
      run: cd ../../src/App/gestoralmacen
    - run: npm install
    - run: npm run build